name: 'npm-publish'
description: 'Publish npm package'
author: 'Conventional Actions'
inputs:
  version:
    required: false
    description: 'version of revive to use'
    default: latest
runs:
  using: 'node24'
  main: 'dist/index.cjs'
branding:
  icon: package
  color: purple
